### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by abhishek7467** [ewrfcas/ZITS-PlusPlus#7]
PS E:\ZITS Inpainting\ZITS__PlusPlus>  python test.py --config configs/config_zitspp.yml  --exp_name model_256  --ckpt_resume ckpts/model_256/models/last.ckpt  --save_path ./outputs/model_256  --img_dir C:\\Users\\spx016\\Downloads\\Testing Image\\test8.jpg  --mask_dir C:\\Users\\spx016\\virtual_Furniture\\maskObj.png  --wf_ckpt ckpts/best_lsm_hawp.pth  --use_ema  --test_size 256  --object_removal
Traceback (most recent call last):
  File "E:\ZITS Inpainting\ZITS__PlusPlus\test.py", line 16, in <module>
    from trainers.nms_temp import get_nms as get_np_nms
  File "E:\ZITS Inpainting\ZITS__PlusPlus\trainers\nms_temp.py", line 15, in <module>
    solver = cdll.LoadLibrary("nms/cxx/lib/solve_csa.so")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spx016\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spx016\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by ewrfcas** [comment]
Sorry, we have not verified the usage of nms in the windows environment.
